### ISSUE TITLE
Code generation improvements

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO-TraitGen#14]
## What

Following on from discoveries and discussions as part of #11

## Tasks

- [ ] [Tests][C++][Python] Test copyright headers added to all generated files
- [ ] [Tests][C++][Python] Add missing tests of hoisting header/module docstrings
- [ ] [Tests][C++][Python] Ensure long docstrings are wrapped appropriately
- [ ] [Core][C++][Python] Choose/create exception type(s) raised when trait property not available
- [ ] [Core][C++][Python] Factor out common utility code
- [ ] [Tests][Python] Test behaviour when requesting trait property of non-imbued trait
- [ ] [Core][Python] Validate module names
- [ ] [Core][Python] Do not duplicate "Conforming" warnings
- [ ] [Core][Python] Remove usage of `TraitBase` and `SpecificationBase`
